# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rai_chat.proto\x12\nfoxchat.ai\"C\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06llm_id\x18\x02 \x01(\t\x12\x13\n\x0bmsg_content\x18\x03 \x01(\t\"\xbd\x01\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x12\n\nblock_type\x18\x03 \x01(\t\x12\x16\n\x0eis_block_start\x18\x04 \x01(\x08\x12\x14\n\x0cis_block_end\x18\x05 \x01(\x08\x12\x0f\n\x07\x65motion\x18\x06 \x01(\t\x12\x12\n\nerror_code\x18\x07 \x01(\x05\x12\x11\n\terror_msg\x18\x08 \x01(\t\x12\x10\n\x08sequence\x18\t \x01(\x05\"0\n\rDeleteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06llm_id\x18\x02 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x93\x01\n\rAIChatService\x12;\n\x04\x43hat\x12\x17.foxchat.ai.ChatRequest\x1a\x18.foxchat.ai.ChatResponse0\x01\x12\x45\n\x0c\x44\x65leteMemory\x12\x19.foxchat.ai.DeleteRequest\x1a\x1a.foxchat.ai.DeleteResponseB$\n\x13\x63om.bedfox.proto.aiB\x0b\x41iChatProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.bedfox.proto.aiB\013AiChatProtoP\000'
  _globals['_CHATREQUEST']._serialized_start=29
  _globals['_CHATREQUEST']._serialized_end=96
  _globals['_CHATRESPONSE']._serialized_start=99
  _globals['_CHATRESPONSE']._serialized_end=288
  _globals['_DELETEREQUEST']._serialized_start=290
  _globals['_DELETEREQUEST']._serialized_end=338
  _globals['_DELETERESPONSE']._serialized_start=340
  _globals['_DELETERESPONSE']._serialized_end=390
  _globals['_AICHATSERVICE']._serialized_start=393
  _globals['_AICHATSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
