bootJar {
    enabled = true
}

dependencies {
    implementation project(':foxChat-common')
    implementation project(':foxChat-pojo')
    implementation project(':foxChat-service')
    implementation project(':foxChat-netty')

    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.data.redis

    // Actuator & Monitoring
    implementation libs.spring.boot.starter.actuator
    implementation libs.micrometer.registry.prometheus

    implementation libs.spring.cloud.starter.openfeign

    implementation libs.mybatis.plus.boot.starter

    implementation libs.commons.lang3
}
